language: ruby
rvm: 2.2
before_script: gem install awesome_bot
script: awesome_bot README.md --allow-dupe --allow-redirect --base-url https://github.com/me-myself-and-aj/soap/blob/master/ --white-list http://documentup.com/profile-org-name/repo-name
